name: prices_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets: 
  - /Users/marche/Documents/FlutterProjects/prices_app/lib/assets/logo/prices_logo.png
  - /Users/marche/Documents/FlutterProjects/prices_app/lib/assets/logo/find.png
